version: 2
jobs:
  test:
    docker:
      - image: insightinfrastructure/icon-ci:v0.5.0
    steps:
      - checkout
      - run:
          name: Apply module
          command: |
            ./.circleci/test-trigger.sh

workflows:
  version: 2
  default:
    jobs:
      - test:
          context: all-provider-ci-1
